import { Inter, Urbanist } from "next/font/google";
import "./globals.css";
import Footer from "@/component/Footer";

const inter = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "EnglishYaari",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>

      </head>
      
      <body className={inter.className}>
        {children}
        <Footer/>
      </body>
      
    </html>
  );
}
